#!/usr/bin/env php
<?php
if (!file_exists('./vendor/autoload.php')) {
    echo "没有安装框架核心，即将自动安装！\n";
    passthru('composer install');
    echo "框架核心安装成功，即将启动！\n";
}
require('./vendor/autoload.php');
$console = new Yao\Console\Console($argv);
$console->run();
