#!/usr/bin/env php
<?php

use Yao\Container;

if (!file_exists('./vendor/autoload.php')) {
    if (function_exists('passthru')) {
        echo "没有安装框架核心，即将自动安装！\n";
        passthru('composer install');
        echo "框架核心安装成功，即将启动！\n";
    } else {
        exit('没有安装框架核心，请使用composer install安装依赖!');
    }
}
define('ROOT_PATH', getcwd() . DIRECTORY_SEPARATOR);
require('./vendor/autoload.php');

$console = Container::instance()->make(\Yao\Console\Console::class, [$argv]);
$console->run();
