<?php

namespace App\Models;

use Yao\Database\Model;

class Users extends Model
{
    /**
     * 表名
     * @var string|null
     */
    public ?string $name = 'users';

    public function create(array $data)
    {
        parent::insert($data); // TODO: Change the autogenerated stub
    }

}