<?php


namespace App\Models;


use Yao\Database\Model;

class Users extends Model
{

    public $name = 'users';

    public function insert(array $data)
    {
        parent::insert($data); // TODO: Change the autogenerated stub
    }

}